### ISSUE TITLE
[REGRESSION]: v1.51.0 Release Workflow broken

### ISSUE THREAD

**Issue by Vinyzu** [Kaliiiiiiiiii-Vinyzu/patchright#43]
See https://github.com/Kaliiiiiiiiii-Vinyzu/patchright/actions/runs/13708938633/job/38340946707#step:8:173.
Probably an update in their Protocol Validator, which we will have to adjust for.
Until the bug is fixed, Release for v1.51.0 will be halted.

**Comment by regseb** [comment]
I think the patch shouldn't modify [`packages/protocol/src/channels.d.ts`](https://github.com/microsoft/playwright/blob/v1.51.1/packages/protocol/src/channels.d.ts#L17) and [`packages/playwright-core/src/protocol/validator.ts`](https://github.com/microsoft/playwright/blob/v1.51.1/packages/playwright-core/src/protocol/validator.ts#L17), as they will be overwritten during the build. The patch should modify [`packages/protocol/src/protocol.yml`](https://github.com/microsoft/playwright/blob/v1.51.1/packages/protocol/src/protocol.yml). And in the workflows, a step must be added to generate `channels.d.ts` and `validator.ts`:

```yaml
      - name: Generate Playwright Channels
        if: steps.version_check.outputs.proceed == 'true'
        # Ignore the error exit code, as the script exits 1 when a file is modified.
        continue-on-error: true
        run: |
          cd playwright
          node utils/generate_channels.js
```
